import type { CostAnalysisRecord, QuotationRecord } from '../../quotation'
import type { StatementRecord } from '../../shipment'

/** 测试用单据。字段齐全，避免每个用例各补一半。 */

export function quotation(overrides: Partial<QuotationRecord> = {}): QuotationRecord {
  return {
    id: 'Q1',
    docNo: 'QTN-20260811-0001',
    version: 1,
    rootId: null,
    customerId: 'C1',
    costAnalysisId: 'CA1',
    template: 'DOMESTIC',
    currency: 'CNY',
    fxRateMicros: null,
    fxQuotedOn: null,
    moldFeeMinor: 120_000n,
    terms: {
      processingMode: '包工包料',
      paymentTerms: '月结30天',
      allowedScrapBps: 300,
      scrapReturned: false,
      leadTime: '25 天',
      remark: '含运费',
    },
    status: 'APPROVED',
    validUntil: new Date(2026, 8, 10),
    submittedBy: 'WFX-2018-0042',
    submittedAt: new Date(2026, 7, 1),
    approvedBy: 'WFX-2015-0007',
    approvedAt: new Date(2026, 7, 2),
    rejectReason: null,
    createdBy: 'WFX-2018-0042',
    versionLock: 0,
    items: [
      {
        id: 'QI1',
        sequence: 1,
        productName: '金属壳体',
        drawingNo: 'BCM-2607',
        drawingVersionId: null,
        revision: 'A',
        material: 'AL6061',
        finishing: '阳极氧化',
        process: '机加工',
        costAnalysisLineId: null,
        remark: '',
        tiers: [
          { id: 'T1', minQuantity: '100.000000', unitPriceMinor: 2500n, unitCostMinor: 2000n, label: null },
          { id: 'T2', minQuantity: '5000.000000', unitPriceMinor: 400n, unitCostMinor: 320n, label: null },
        ],
      },
    ],
    ...overrides,
  } as QuotationRecord
}

export function costAnalysis(overrides: Partial<CostAnalysisRecord> = {}): CostAnalysisRecord {
  return {
    id: 'CA1',
    docNo: 'CST-20260811-0001',
    version: 1,
    rootId: null,
    customerId: 'C1',
    productModel: 'M26-P09',
    lossBps: 500,
    overheadBps: 500,
    vatBps: 1300,
    currency: 'CNY',
    processColumns: [
      { key: 'deburring', label: '打磨去毛刺' },
      { key: 'polishing', label: '抛光' },
    ],
    status: 'COMPLETED',
    preparedBy: 'WFX-2019-0011',
    completedAt: new Date(2026, 7, 3),
    versionLock: 0,
    lines: [
      {
        id: 'CL1',
        sequence: 1,
        blankType: '铝板料',
        drawingNo: 'BCM-2607',
        drawingVersionId: null,
        spec: '115*106*19',
        revision: 'A',
        quantity: '1.000000',
        material: 'AL6061-T6',
        estimatedWeightKg: '1.030000',
        netWeightKg: '0.143000',
        scrapWeightKg: '0.887000',
        scrapUnitPriceMinor: 0n,
        materialUnitPriceMinor: 2900n,
        materialPriceOverridden: false,
        materialPriceSourceId: null,
        machiningMethod: 'CNC',
        machiningMinutes: '180.000000',
        machiningCostMinor: 18_000n,
        processCosts: { deburring: 150n, polishing: 0n },
        remark: '',
      },
    ],
    ...overrides,
  } as CostAnalysisRecord
}

export function statement(overrides: Partial<StatementRecord> = {}): StatementRecord {
  return {
    id: 'ST1',
    docNo: 'STM-20260811-0001',
    customerId: 'C1',
    periodFrom: new Date(2026, 6, 1),
    periodTo: new Date(2026, 6, 31),
    currency: 'CNY',
    version: 1,
    openingBalanceMinor: 0n,
    shippedAmountMinor: 500_000n,
    invoicedAmountMinor: 500_000n,
    receivedAmountMinor: 0n,
    returnAmountMinor: -30_000n,
    closingBalanceMinor: 470_000n,
    differenceAmountMinor: 0n,
    differenceNote: null,
    overdueAmountMinor: 0n,
    status: 'SENT',
    ownerUserCode: 'WFX-2018-0042',
    sentAt: new Date(2026, 7, 1),
    confirmedAt: null,
    versionLock: 0,
    lines: [
      {
        id: 'SL1',
        sequence: 1,
        occurredAt: new Date(2026, 6, 20),
        type: 'SHIPMENT',
        docNo: 'SHP-20260720-0001',
        productName: '金属壳体',
        quantity: '100.000000',
        amountMinor: 500_000n,
        matched: true,
        remark: null,
      },
      {
        id: 'SL2',
        sequence: 2,
        occurredAt: new Date(2026, 6, 28),
        type: 'RETURN',
        docNo: 'RMA-20260728-0001',
        productName: '金属壳体',
        quantity: '6.000000',
        amountMinor: -30_000n,
        matched: true,
        remark: '尺寸超差',
      },
    ],
    ...overrides,
  } as StatementRecord
}
